# Generated by Django 4.2.7 on 2023-11-23 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicacion', '0002_remove_familia_jefe_de_familia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Banco',
            },
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bloque', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Bloque',
            },
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_calle', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Calle',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('idfamilia', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Familia',
            },
        ),
        migrations.CreateModel(
            name='Nivel_Educ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Nivel', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Nivel_educ',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Profesion',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero')], default='V', max_length=50)),
                ('posee_cedula', models.BooleanField(default=True)),
                ('cedula', models.CharField(blank=True, max_length=12, null=True)),
                ('P_nombre', models.CharField(max_length=100)),
                ('P_apellido', models.CharField(max_length=100)),
                ('S_nombre', models.CharField(max_length=100, null=True)),
                ('S_apellido', models.CharField(max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('parentesco', models.CharField(blank=True, choices=[('P', 'Madre/Padre'), ('E', 'Conyuge'), ('N', 'Nuera/Yerno'), ('S', 'Suegro/a'), ('A', 'Abuelo/a'), ('N', 'Nieto/a'), ('H', 'Hermano/o'), ('C', 'Cuñado/a'), ('T', 'Tío/a'), ('S', 'Sobrino/a'), ('h', 'Hijo/a'), ('p', 'Primo/a'), ('C', 'Concubino/a')], default='n', max_length=20)),
                ('estado_civil', models.CharField(choices=[('c', 'Casado/a'), ('s', 'Soltero/a'), ('d', 'Divorciad/o'), ('e', 'Concubinato')], default='s', max_length=1)),
                ('trabaja', models.BooleanField(default=False)),
                ('descripcion_trabajo', models.TextField(blank=True)),
                ('ocupacion', models.BooleanField()),
                ('descripcion_ocupacion', models.TextField(blank=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('celular', models.CharField(max_length=15, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('discapacidad', models.BooleanField()),
                ('descripcion_discapacidad', models.TextField(blank=True)),
                ('tipo_vivienda', models.CharField(choices=[('casa_unifamiliar', 'Casa Unifamiliar'), ('apartamento', 'Apartamento'), ('Casa_T_Zinc', 'Casa de Techo de Zinc'), ('casa_campo', 'Casa de Campo'), ('condominio', 'Condominio'), ('quinta', 'Quinta'), ('vivienda_social', 'Vivienda de Interés Social'), ('vivienda_prefabricada', 'Vivienda Prefabricada'), ('chalet', 'Chalet'), ('duplex', 'Dúplex')], default='casa_unifamiliar', max_length=21)),
                ('num_casa', models.IntegerField()),
                ('jefe_familia', models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], default=0)),
                ('carga_familiar', models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('familia_r', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familia_personas', to='aplicacion.familia')),
                ('nivel_educ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.nivel_educ')),
                ('num_bloque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.bloque')),
                ('num_calle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.calle')),
                ('profesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.profesion')),
            ],
            options={
                'db_table': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('idPagos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('numero_referencia', models.CharField(max_length=45)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('banco_emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_emisor', to='aplicacion.banco')),
                ('banco_receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_receptor', to='aplicacion.banco')),
                ('jefe_de_familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.familia')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.AddField(
            model_name='familia',
            name='jefe_de_familia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familia_jefe', to='aplicacion.persona'),
        ),
    ]
