# Generated by Django 4.2.3 on 2023-11-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='posee_cedula',
        ),
        migrations.AddField(
            model_name='persona',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_documento',
            field=models.CharField(choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte'), ('ninguno', 'Ninguno')], max_length=10, null=True),
        ),
    ]
