# Generated by Django 4.2.3 on 2023-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_remove_persona_posee_cedula_persona_pasaporte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='persona',
            name='posee_cedula',
            field=models.BooleanField(default=True),
        ),
    ]
